[package]
name = "matcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
serde_json = { version = "1.0.108", features = [] }
arrayvec = "0.5.1"